language: node_js
node_js: 
  - 16
# safelist
branches:
  only:
  - main
env:
  global:
    - CLOUD_RUN_REGION=us-west1
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1   # prevent gcloud from prompting
before_install:
  - openssl aes-256-cbc -K $encrypted_a379b7f18ce4_key -iv $encrypted_a379b7f18ce4_iv -in som-rit-relief-app.json.enc -out som-rit-relief-app.json -d
  - if [ ! -d "/opt/pyenv/versions/3.8.10" ]; then pyenv install 3.8.10; pyenv global 3.8.10; fi
  - gcloud auth activate-service-account --key-file=som-rit-relief-app.json
  - gcloud auth configure-docker        # enable "docker push" to gcr
  - gcloud config set project "som-rit-relief-app"
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
script:
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  # Add gcloud to $PATH
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version
  - |
    set -ex;
    npm run build && \
    gcloud app deploy app.yaml
    set +x