runtime: nodejs16

instance_class: F2

service: default

env_variables:
  REACT_APP_BACKEND_URL: "https://analyze-j2igbnbiba-uw.a.run.app/analyze"

handlers:
  # Serve all static files with url ending with a file extension
  - url: /service-worker.js
    static_files: build/service-worker.js
    upload: build/service-worker.js
    mime_type: application/javascript
    expiration: 0m

  - url: /(.*\.js)$
    secure: always
    static_files: build/\1
    upload: build/.*\.js$
    mime_type: application/javascript

  - url: /(.*\.m4a)$
    secure: always
    static_files: build/\1
    upload: build/.*\.m4a$
    http_headers:
      Accept-Ranges: bytes
      
  - url: /(.*\.(css|png|jpg|svg|ico|gif|mp3))$
    secure: always
    static_files: build/\1
    upload: build/.*\.(css|png|jpg|svg|ico|gif|mp3)$

  - url: /(.*\.json)
    mime_type: application/json
    static_files: static/\1
    upload: static/(.*\.json)

  # Catch all handler to index.html
  - url: /(.+)/
    static_files: static/\1/index.html
    upload: static/(.+)/index.html

  # site root
  - url: /
    static_files: static/index.html
    upload: static/index.html