runtime: nodejs18

instance_class: F2

service: default

env_variables:
  REACT_APP_BACKEND_URL: "https://analyze-j2igbnbiba-uw.a.run.app/analyze"

handlers:
  # Serve all static files with url ending with a file extension
  - url: /service-worker.js
    static_files: build/service-worker.js
    upload: build/service-worker.js
    mime_type: application/javascript
    expiration: 0m
  
  - url: /manifest.json
    static_files: build/manifest.json
    upload: build/manifest.json
  
  - url: /(.*\.js)$
    secure: always
    static_files: build/\1
    upload: build/.*\.js$
    mime_type: application/javascript

  - url: /(.*\.m4a)$
    secure: always
    static_files: build/\1
    upload: build/.*\.m4a$
    http_headers:
      Accept-Ranges: bytes
      
  - url: /(.*\.(css|map|png|jpg|svg|ico|json|gif|mp3|map))$
    secure: always
    static_files: build/\1
    upload: build/.*\.(css|map|png|jpg|svg|ico|json|gif|mp3|map)$
    # http_headers:
    #   Accept_Ranges: bytes

  # - url: /(.*\..+)$
  #   static_files: build/\1
  #   upload: build/(.*\..+)$


  # Catch all handler to index.html
  - url: /.*
    static_files: build/index.html
    upload: build/index.html