version: '3'
services:
    app:
        build:
            context: .
        restart: always
        stdin_open: true
        ports:
            - "3000:3000"
            - "9222:9222" # Debug root
        environment:
            - WATCHPACK_POLLING=true
            - FAST_REFRESH=false 
            - WDS_SOCKET_PORT=0 # Necessary for hot reload
        volumes:
            - .:/app
            - /app/node_modules
volumes:
  node_modules:
