version: '3'
services:
    app:
        build:
            context: .
        restart: always
        stdin_open: true
        ports:
            - "5555:3000"
        environment:
            - WATCHPACK_POLLING=true
            - FAST_REFRESH=false 
            - WDS_SOCKET_PORT=0 # Necessary for hot reload
        volumes:
            - './:/app'
            - 'node_modules:/app/node_modules'
volumes:
  node_modules:
