/* eslint-disable no-restricted-globals */

// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other
// code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, CacheFirst } from 'workbox-strategies';
import {RangeRequestsPlugin} from 'workbox-range-requests';
import {CacheableResponsePlugin} from 'workbox-cacheable-response';

// Your service worker needs to import dexie and you should declare your db within the service worker itself or in a script that it will import.
// You can also use es6 imports and compile the service worker using webpack but in any case the db instance has to live within the service worker. You can also have another db instance in the DOM that talks to the same DB.
import { db_audios } from "./database/db"

clientsClaim();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA


// This will filter out all manifest entries with URLs ending in .m4a
// Adjust the criteria as needed.
//https://stackoverflow.com/questions/67118051/filtering-out-assets-from-precaching-in-create-react-app
// const filteredManifest = self.__WB_MANIFEST;
const filteredManifest = self.__WB_MANIFEST.filter((entry) => {
    return !entry.url.endsWith('.m4a');
});
precacheAndRoute(filteredManifest);

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell. Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
  // Return false to exempt requests from being fulfilled by index.html.
  ({ request, url }) => {
    // If this isn't a navigation, skip.
    if (request.mode !== 'navigate') {
      return false;
    } // If this is a URL that starts with /_, skip.

    if (url.pathname.startsWith('/_')) {
      return false;
    } // If this looks like a URL for a resource, because it contains // a file extension, skip.

    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    } // Return true to signal that we want to use the handler.

    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html')
);

// An example runtime caching route for requests that aren't handled by the
// precache, in this case same-origin .png requests like those from in public/
registerRoute(
  // Add in any other file extensions or routing criteria as needed.
  ({ url }) => url.origin === self.location.origin && url.pathname.endsWith('.png'), // Customize this strategy as needed, e.g., by changing to CacheFirst.
  new StaleWhileRevalidate({
    cacheName: 'images',
    plugins: [
        // Ensure that once this runtime cache reaches a maximum size the
        // least-recently used images are removed.
        new ExpirationPlugin({ maxEntries: 100 }),
        // Only requests that return with a 200 status are cached
        new CacheableResponsePlugin({
            statuses: [200],
        }),
    ],
  })
);

async function fetchCacheAudio(event, title){
    try {
        const response = await fetch(event.request, {headers: {'Range': 'bytes=0-'}});
        if (!response.ok) {
            throw new Error(`Failed to fetch data from URL: ${event.request}`);
        }

        let responseClone   = response.clone();
        const data_clone    = await responseClone.blob();

        //has data! , stuff it in IndexDB
        const audio = {
            title: title,
            data: data_clone
        };
        db_audios.files.put(audio);

        console.log("4a inside the network fetch to get m4a file, clone response BLOB to cache in indexDB, return Response object for original response blob", data_clone);

        var headers = {
            'Content-Type': 'audio/mpeg',
            'Accept-Ranges': 'bytes',
            'Content-Length': response.headers.get('Content-Length')
        };

        // Set the Content-Range header to enable byte-range requests in Safari
        var rangeHeader = event.request.headers.get('range');

        if (rangeHeader) {
            var totalSize   = response.headers.get('Content-Length');
            var range       = rangeHeader.match(/(\d+)-(\d*)/);
            var start       = parseInt(range[1], 10);
            var end         = range[2] ? parseInt(range[2], 10) : totalSize - 1;
            var chunkSize   = end - start + 1;

            headers['Content-Range'] = 'bytes ' + start + '-' + end + '/' + totalSize;
            headers['Content-Length'] = chunkSize;

            console.log("so if rangeheader , then do this, otherwise return as normal", headers);
            return response.arrayBuffer().then(function(buffer) {
                var slicedBuffer    = buffer.slice(start, end + 1);
                var slicedBlob      = new Blob([slicedBuffer], { type: 'audio/mpeg' });
                return new Response(slicedBlob, {
                    status: 206,
                    statusText: 'Partial Content',
                    headers: headers
                });
            });
        } else {
            const data = await response.blob();

            return new Response(data, {
                headers: headers
            });
        }
    } catch (error) {
        console.error(error);
    }
}
async function getAudioFileByTitle(title, event) {
    const audioRecord = await db_audios.files.where({ title: title }).first();
    console.log("2 inside getAudioFileByTitle check indexDb for file", audioRecord);

    if(!audioRecord){
        console.log("3 none found, so fetch from network");
        let returnResponse = await fetchCacheAudio(event, title);
        console.log("4b fetched data , cached in indexDB, returning the blob  itself", returnResponse);

        return returnResponse;
    }else{
        const filesize = audioRecord.data.size;

        console.log("3 & 4 found in INDEXDB!!", title, audioRecord.data, filesize);

        var headers = {
            'Content-Type': 'audio/mpeg',
            'Accept-Ranges': 'bytes',
            'Content-Length': filesize
        };

        // Set the Content-Range header to enable byte-range requests in Safari
        var rangeHeader = event.request.headers.get('range');

        if (rangeHeader) {
            var totalSize   = filesize;
            var range       = rangeHeader.match(/(\d+)-(\d*)/);
            var start       = 0;
            var end         = totalSize - 1;
            var chunkSize   = end - start + 1;

            headers['Content-Range'] = 'bytes ' + start + '-' + end + '/' + totalSize;
            headers['Content-Length'] = chunkSize;

            console.log("so if rangeheader , even if fucking cached from indexDB", headers);

            return new Response(audioRecord.data, {
                status: 206,
                statusText: 'Partial Content',
                headers: headers
            });
        } else {
            console.log("if it is in cache, will it still do a two stage request in safari? will it get here?");
            return new Response(audioRecord.data, {
                headers: headers
            });
        }
    }
}

self.addEventListener('fetch', function(event) {
    const url       = new URL(event.request.url);
    const fileName  = url.pathname.split('/').pop();

    if (fileName.endsWith(".m4a")) {
        console.log("1 found fileName partial ends with m4a", fileName);
        event.respondWith(
            new Promise(async (resolve) => {
                let response = await getAudioFileByTitle(fileName, event);
                console.log("5 , should return a response object with proper headers", response.headers.get("Content-Type"), response.headers.get("Accept-Ranges"), response.headers.get("Content-Length"));
                resolve(response);
            })
        );
    }else{
        event.respondWith(fetch(event.request));
    }
});




















// Any other custom service worker logic can go here.
// var version = '2'
// registerRoute(
//   /.*\.m4a/,
//   cacheFirst({
//     cacheName: 'your-cache-name-here',
//     plugins: [
//       new workbox.cacheableResponse.Plugin({statuses: [200]}),
//       new workbox.rangeRequests.Plugin(),
//     ],
//   }),
// );
// registerRoute(
//   ({url, request, event}) => {
//     const {destination} = request;
//     console.log('url', url)
//     console.log('request', request)
//     console.log('event', event)
//     return destination === 'video' || destination === 'audio'
//   },
//   new CacheFirst({
//     cacheName: 'v1-cache-audio',
//     plugins: [
//       new CacheableResponsePlugin({
//         statuses: [200]
//       }),
//       new RangeRequestsPlugin(),
//     ],
//   }),
// );

// var version = 2;
// var staticCacheName = `cache-v${version}`
// self.addEventListener('fetch', function(event) {
//   var url = new URL(event.request.url);
//   if (url.pathname.match(/^\/((assets|images)\/|manifest.json$)/)) {
//     if (event.request.headers.get('range')) {
//       event.respondWith(returnRangeRequest(event.request, staticCacheName));
//     } else {
//       event.respondWith(returnFromCacheOrFetch(event.request, staticCacheName));
//     }
//   }
//   // other strategies
// });

// function returnRangeRequest(request, cacheName) {
//   return caches
//     .open(cacheName)
//     .then(function(cache) {
//       return cache.match(request.url);
//     })
//     .then(function(res) {
//       if (!res) {
//         return fetch(request)
//           .then(res => {
//             const clonedRes = res.clone();
//             return caches
//               .open(cacheName)
//               .then(cache => cache.put(request, clonedRes))
//               .then(() => res);
//           })
//           .then(res => {
//             return res.arrayBuffer();
//           });
//       }
//       return res.arrayBuffer();
//     })
//     .then(function(arrayBuffer) {
//       const bytes = /^bytes\=(\d+)\-(\d+)?$/g.exec(
//         request.headers.get('range')
//       );
//       if (bytes) {
//         const start = Number(bytes[1]);
//         const end = Number(bytes[2]) || arrayBuffer.byteLength - 1;
//         return new Response(arrayBuffer.slice(start, end + 1), {
//           status: 206,
//           statusText: 'Partial Content',
//           headers: [
//             ['Content-Range', `bytes ${start}-${end}/${arrayBuffer.byteLength}`]
//           ]
//         });
//       } else {
//         return new Response(null, {
//           status: 416,
//           statusText: 'Range Not Satisfiable',
//           headers: [['Content-Range', `*/${arrayBuffer.byteLength}`]]
//         });
//       }
//     });
// }